name: Delete All Firebase Users

on:
  schedule:
    # This cron syntax means "run every minute"
    - cron: '* * * * *' # Runs every minute
  workflow_dispatch: # Allows you to trigger it manually if needed

jobs:
  delete_all_users:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install firebase-admin

      - name: Delete all users
        run: |
          echo "const admin = require('firebase-admin');" > deleteAllUsers.js
          echo "admin.initializeApp({ credential: admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT)) });" >> deleteAllUsers.js
          echo "async function deleteAllUsers() {" >> deleteAllUsers.js
          echo "  try {" >> deleteAllUsers.js
          echo "    const users = await admin.auth().listUsers(); // List all users" >> deleteAllUsers.js
          echo "    for (const user of users.users) {" >> deleteAllUsers.js
          echo "      await admin.auth().deleteUser(user.uid); // Delete user" >> deleteAllUsers.js
          echo "      console.log('Deleted user:', user.email);" >> deleteAllUsers.js
          echo "    }" >> deleteAllUsers.js
          echo "  } catch (error) {" >> deleteAllUsers.js
          echo "    console.error('Error deleting users:', error);" >> deleteAllUsers.js
          echo "  }" >> deleteAllUsers.js
          echo "}" >> deleteAllUsers.js
          echo "deleteAllUsers();" >> deleteAllUsers.js

      - name: Run user deletion script
        run: |
          node deleteAllUsers.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
